export const column = [
  {
    key: "orderStyle",
    prop: "orderStyle",
    label: "订单类型",
    fixed: "left",
    minWidth: 90,
    align: "left",
  },
  {
    key: "orderNumbers",
    prop: "orderNumbers",
    label: "单号",
    fixed: "left",
    minWidth: 250,
    align: "left",
  },
  {
    key: "platform",
    prop: "platform",
    label: "平台/店铺",
    minWidth: 200,
    align: "center",
  },
  {
    key: "brand",
    prop: "brand",
    label: "品牌/品类",
    minWidth: 150,
    fiterCode: "brand",
    needFilter: true,
    align: "center",
  },
  {
    key: "sku",
    prop: "sku",
    label: "产品型号",
    minWidth: 200,
    align: "left",
  },
  {
    key: "quantity",
    prop: "quantity",
    label: "数量",
    minWidth: 90,
    align: "center",
  },
  {
    key: "address",
    prop: "address",
    label: "收货地",
    minWidth: 200,
    align: "center",
  },

  {
    key: "lastShippingTime",
    prop: "lastShippingTime",
    label: "最晚发货时间",
    minWidth: 180,
    align: "center",
  },
  {
    key: "erpTradeTime",
    prop: "erpTradeTime",
    label: "erp交易时间",
    minWidth: 180,
    align: "center",
  },
];