<template>
  <div class="app-container subsidy-products">
    <section class="card"><el-form :inline="true" :model="query"><el-form-item label="商品名称"><el-input v-model="query.productName" clearable /></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable><el-option label="上架" :value="1" /><el-option label="下架" :value="0" /></el-select></el-form-item><el-button type="primary" @click="load">查询</el-button><el-button @click="open()">新增商品</el-button></el-form></section>
    <section class="card"><el-table v-loading="loading" :data="rows" border><el-table-column prop="productCode" label="编码" /><el-table-column prop="productName" label="商品名称" /><el-table-column prop="categoryId" label="分类" /><el-table-column label="状态"><template slot-scope="scope"><el-tag :type="scope.row.status === 1 ? 'success' : 'info'">{{ scope.row.status === 1 ? '上架' : '下架' }}</el-tag></template></el-table-column><el-table-column label="操作"><template slot-scope="scope"><el-button type="text" @click="open(scope.row)">编辑</el-button></template></el-table-column></el-table><pagination v-show="total > 0" :total="total" :page.sync="query.pageNum" :limit.sync="query.pageSize" @pagination="load" /></section>
    <el-dialog :title="form.id ? '编辑商品' : '新增商品'" :visible.sync="visible" width="640px"><el-form ref="form" :model="form" :rules="rules" label-width="100px"><el-form-item label="分类ID" prop="categoryId"><el-input v-model.number="form.categoryId" /></el-form-item><el-form-item label="商品编码" prop="productCode"><el-input v-model="form.productCode" /></el-form-item><el-form-item label="商品名称" prop="productName"><el-input v-model="form.productName" /></el-form-item><el-form-item label="主图地址"><el-input v-model="form.mainImageUrl" /></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio :label="1">上架</el-radio><el-radio :label="0">下架</el-radio></el-radio-group></el-form-item></el-form><span slot="footer"><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></span></el-dialog>
  </div>
</template>
<script>
import { addSubsidyProduct, getSubsidyProducts, updateSubsidyProduct } from '@/api/subsidy'
export default { name: 'SubsidyProducts', data() { return { loading: false, visible: false, total: 0, rows: [], query: { productName: '', status: null, pageNum: 1, pageSize: 10 }, form: {}, rules: { categoryId: [{ required: true, message: '请输入分类ID', trigger: 'blur' }], productCode: [{ required: true, message: '请输入商品编码', trigger: 'blur' }], productName: [{ required: true, message: '请输入商品名称', trigger: 'blur' }] } } }, created() { this.load() }, methods: { load() { this.loading = true; getSubsidyProducts(this.query).then(response => { this.rows = response.rows || []; this.total = response.total || 0 }).finally(() => { this.loading = false }) }, open(row) { this.form = Object.assign({ categoryId: null, productCode: '', productName: '', subtitle: '', mainImageUrl: '', detailContent: '', recommended: 0, sortOrder: 0, status: 1 }, row || {}); this.visible = true }, save() { this.$refs.form.validate(valid => { if (!valid) return; const request = this.form.id ? updateSubsidyProduct(this.form.id, this.form) : addSubsidyProduct(this.form); request.then(() => { this.$message.success('保存成功'); this.visible = false; this.load() }) }) } } }
</script>
<style lang="scss" scoped>.subsidy-products{min-height:100%;background:var(--bg-page)}.card{padding:20px;margin-bottom:16px;background:var(--bg-card);border:1px solid var(--border-tags);border-radius:var(--radius);box-shadow:var(--shadow-card)}</style>
