<template>
  <div class="app-container">
    <el-card shadow="never">
      <el-form :inline="true"><el-form-item label="商品 ID"><el-input-number v-model="productId" :min="1" /></el-form-item><el-button type="primary" @click="load">查询 SKU</el-button><el-button :disabled="!productId" @click="openSku()">新增 SKU</el-button></el-form>
      <el-table v-loading="loading" :data="rows" border>
        <el-table-column prop="skuCode" label="SKU 编码" min-width="150" /><el-table-column prop="specName" label="规格" min-width="150" /><el-table-column prop="originalPrice" label="原价" width="110" /><el-table-column prop="stockQuantity" label="库存" width="90" /><el-table-column prop="salesQuantity" label="销量" width="90" /><el-table-column label="状态" width="90"><template slot-scope="scope"><el-tag :type="scope.row.status === 1 ? 'success' : 'info'">{{ scope.row.status === 1 ? '上架' : '下架' }}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template slot-scope="scope"><el-button type="text" @click="openSku(scope.row)">编辑</el-button><el-button type="text" @click="openAdjust(scope.row)">调库存</el-button></template></el-table-column>
      </el-table>
    </el-card>
    <el-dialog :title="sku.id ? '编辑 SKU' : '新增 SKU'" :visible.sync="skuVisible" width="500px"><el-form ref="sku" :model="sku" :rules="skuRules" label-width="90px"><el-form-item label="SKU 编码" prop="skuCode"><el-input v-model="sku.skuCode" /></el-form-item><el-form-item label="规格" prop="specName"><el-input v-model="sku.specName" /></el-form-item><el-form-item label="原价" prop="originalPrice"><el-input-number v-model="sku.originalPrice" :min="0" :precision="2" /></el-form-item><el-form-item label="初始库存" prop="stockQuantity"><el-input-number v-model="sku.stockQuantity" :min="0" /></el-form-item><el-form-item label="状态"><el-radio-group v-model="sku.status"><el-radio :label="1">上架</el-radio><el-radio :label="0">下架</el-radio></el-radio-group></el-form-item></el-form><span slot="footer"><el-button @click="skuVisible=false">取消</el-button><el-button type="primary" @click="saveSku">保存</el-button></span></el-dialog>
    <el-dialog title="库存调整" :visible.sync="adjustVisible" width="440px"><el-alert title="允许调整至负库存；请填写可追溯的调整原因。" type="warning" :closable="false" class="notice" /><el-form ref="adjust" :model="adjust" :rules="adjustRules" label-width="90px"><el-form-item label="调整数量" prop="delta"><el-input-number v-model="adjust.delta" /></el-form-item><el-form-item label="调整原因" prop="remark"><el-input v-model="adjust.remark" maxlength="256" show-word-limit /></el-form-item></el-form><span slot="footer"><el-button @click="adjustVisible=false">取消</el-button><el-button type="primary" @click="saveAdjust">确认调整</el-button></span></el-dialog>
  </div>
</template>

<script>
import { adjustSubsidyInventory, getSubsidySkus, saveSubsidySku, updateSubsidySku } from '@/api/subsidy'
export default { name: 'SubsidySkus', data() { return { productId: null, loading: false, rows: [], skuVisible: false, adjustVisible: false, currentSkuId: null, sku: {}, adjust: {}, skuRules: { skuCode: [{ required: true, message: '请输入 SKU 编码', trigger: 'blur' }], originalPrice: [{ required: true, message: '请输入原价', trigger: 'change' }] }, adjustRules: { delta: [{ required: true, message: '请输入调整数量', trigger: 'change' }], remark: [{ required: true, message: '请输入调整原因', trigger: 'blur' }] } } }, methods: { load() { if (!this.productId) return; this.loading = true; getSubsidySkus(this.productId).then(response => { this.rows = response.data || [] }).finally(() => { this.loading = false }) }, openSku(row) { this.sku = Object.assign({ productId: this.productId, skuCode: '', specName: '', originalPrice: 0, stockQuantity: 0, status: 1 }, row || {}); this.skuVisible = true }, saveSku() { this.$refs.sku.validate(valid => { if (!valid) return; const request = this.sku.id ? updateSubsidySku(this.sku.id, this.sku) : saveSubsidySku(this.sku); request.then(() => { this.$message.success('保存成功'); this.skuVisible = false; this.load() }) }) }, openAdjust(row) { this.currentSkuId = row.id; this.adjust = { delta: 0, remark: '' }; this.adjustVisible = true }, saveAdjust() { this.$refs.adjust.validate(valid => { if (!valid) return; adjustSubsidyInventory(this.currentSkuId, this.adjust).then(() => { this.$message.success('库存已调整'); this.adjustVisible = false; this.load() }) }) } } }
</script>

<style lang="scss" scoped>.notice { margin-bottom: 16px; }</style>
