-- 吉客云销售渠道主数据；仅保存主数据，不保存同步游标。
CREATE TABLE IF NOT EXISTS `m_sales_channel` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `jky_channel_id` bigint NOT NULL COMMENT '吉客云渠道ID',
    `channel_code` varchar(64) NOT NULL DEFAULT '' COMMENT '渠道编码',
    `channel_name` varchar(255) NOT NULL DEFAULT '' COMMENT '渠道名称',
    `channel_type` int DEFAULT NULL COMMENT '渠道类型',
    `platform_code` varchar(64) DEFAULT NULL COMMENT '平台编码',
    `platform_name` varchar(128) DEFAULT NULL COMMENT '平台名称',
    `channel_department_id` bigint DEFAULT NULL COMMENT '渠道部门ID',
    `channel_department_name` varchar(128) DEFAULT NULL COMMENT '渠道部门名称',
    `jky_subject_id` bigint DEFAULT NULL COMMENT '吉客云经营主体ID',
    `subject_name` varchar(255) DEFAULT NULL COMMENT '经营主体名称',
    `warehouse_code` varchar(64) DEFAULT NULL COMMENT '仓库编码',
    `warehouse_name` varchar(128) DEFAULT NULL COMMENT '仓库名称',
    `contact_name` varchar(64) DEFAULT NULL COMMENT '联系人',
    `contact_phone` varchar(64) DEFAULT NULL COMMENT '联系电话',
    `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
    `address` varchar(500) DEFAULT NULL COMMENT '地址',
    `country_name` varchar(64) DEFAULT NULL COMMENT '国家',
    `province_name` varchar(64) DEFAULT NULL COMMENT '省份',
    `city_name` varchar(64) DEFAULT NULL COMMENT '城市',
    `town_name` varchar(64) DEFAULT NULL COMMENT '区县',
    `memo` varchar(1000) DEFAULT NULL COMMENT '备注',
    `last_sync_time` datetime NOT NULL COMMENT '最后同步时间',
    `created_time` datetime NOT NULL COMMENT '创建时间',
    `updated_time` datetime NOT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_m_sales_channel_jky_channel_id` (`jky_channel_id`),
    KEY `idx_m_sales_channel_code` (`channel_code`),
    KEY `idx_m_sales_channel_name` (`channel_name`),
    KEY `idx_m_sales_channel_platform_name` (`platform_name`),
    KEY `idx_m_sales_channel_subject_name` (`subject_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='吉客云销售渠道主数据';
