-- 吉客云经营主体主数据表：独立于供应商 u_company。
CREATE TABLE IF NOT EXISTS `m_subject` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `jky_subject_id` bigint NOT NULL COMMENT '吉客云经营主体ID',
    `subject_code` varchar(64) NOT NULL DEFAULT '' COMMENT '主体编码',
    `subject_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主体名称',
    `subject_short_name` varchar(255) DEFAULT NULL COMMENT '主体简称',
    `country_name` varchar(64) DEFAULT NULL COMMENT '国家',
    `province_name` varchar(64) DEFAULT NULL COMMENT '省份',
    `city_name` varchar(64) DEFAULT NULL COMMENT '城市',
    `town_name` varchar(64) DEFAULT NULL COMMENT '区县',
    `address` varchar(500) DEFAULT NULL COMMENT '详细地址',
    `contact_name` varchar(64) DEFAULT NULL COMMENT '联系人',
    `contact_phone` varchar(64) DEFAULT NULL COMMENT '联系电话',
    `tax_identify_number` varchar(64) DEFAULT NULL COMMENT '税号',
    `is_blockup` tinyint NOT NULL DEFAULT 0 COMMENT '吉客云停用标记：1停用，0正常',
    `is_delete` tinyint NOT NULL DEFAULT 0 COMMENT '吉客云删除标记：1删除，0未删除',
    `source_created_time` bigint DEFAULT NULL COMMENT '吉客云创建时间戳',
    `source_modified_time` bigint DEFAULT NULL COMMENT '吉客云修改时间戳',
    `last_sync_time` datetime NOT NULL COMMENT '最后同步时间',
    `created_time` datetime NOT NULL COMMENT '创建时间',
    `updated_time` datetime NOT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_m_subject_jky_subject_id` (`jky_subject_id`),
    KEY `idx_m_subject_code` (`subject_code`),
    KEY `idx_m_subject_name` (`subject_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='经营主体主数据';
