-- 拼多多增量订单表
CREATE TABLE `pdd_order_increment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_sn` varchar(64) NOT NULL COMMENT '订单号',
  `payer_config_id` bigint(20) DEFAULT NULL COMMENT '付款主体ID',
  `payer_name` varchar(128) DEFAULT NULL COMMENT '付款主体名称',
  `receiver_name` varchar(64) DEFAULT NULL COMMENT '收件人姓名',
  `receiver_phone` varchar(32) DEFAULT NULL COMMENT '收件人手机号',
  `receiver_address` varchar(512) DEFAULT NULL COMMENT '收件人完整地址',
  `province` varchar(64) DEFAULT NULL COMMENT '省份',
  `city` varchar(64) DEFAULT NULL COMMENT '城市',
  `district` varchar(64) DEFAULT NULL COMMENT '区/县',
  `address` varchar(256) DEFAULT NULL COMMENT '详细地址',
  `goods_name` varchar(256) DEFAULT NULL COMMENT '商品名称',
  `spec` varchar(256) DEFAULT NULL COMMENT '商品规格',
  `order_quantity` int(11) DEFAULT NULL COMMENT '商品数量',
  `order_status` int(11) DEFAULT NULL COMMENT '订单状态(1:待发货 2:已发货 3:已完成 4:已取消 5:售后中)',
  `refund_status` int(11) DEFAULT NULL COMMENT '售后状态(0:无售后 1:售后中 2:售后成功)',
  `trade_type` int(11) DEFAULT NULL COMMENT '交易类型(0:普通订单 1:定金订单)',
  `is_lucky_flag` int(11) DEFAULT NULL COMMENT '是否百亿补贴(0:否 1:是)',
  `created_time` bigint(20) DEFAULT NULL COMMENT '订单创建时间(时间戳)',
  `updated_time` bigint(20) DEFAULT NULL COMMENT '订单更新时间(时间戳)',
  `end_updated_at` bigint(20) DEFAULT NULL COMMENT '数据抓取结束时间(用于下次增量查询的起始时间)',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` int(11) DEFAULT '0' COMMENT '是否被删除 0 未删除 1 已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_sn` (`order_sn`),
  KEY `idx_payer_config_id` (`payer_config_id`),
  KEY `idx_end_updated_at` (`end_updated_at`),
  KEY `idx_order_status` (`order_status`),
  KEY `idx_created_time` (`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='拼多多增量订单表';